We have to add numpy to call array. We have to import numpy and put the shortform np

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,0,0])

For example we want to test the summation of a and b array

In [3]:
a+b

array([2, 2, 3])

and test for 0.5 multiply by a

In [2]:
0.5*a

array([0.5, 1. , 1.5])

To create 0 vector or 0 matrix use np.zeros command

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

All standard matrix operations can be done using matrix product

In [11]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
np.dot(a,b)

array([[4, 1],
       [2, 2]])